### ISSUE TITLE
Must create a game to see game list after log in

### ISSUE THREAD

**Issue by kadenbarlow** [cs340tabyu/cs340Fall2017#11]
Open App after having created games
Assert game list empty
Create game to see list populated

Note this is when you log in not when you register

**Comment by bderbidge** [comment]
couldn't recreate this issue

**Comment by kadenbarlow** [comment]
We were able to do this more than once

**Comment by pbstrein** [comment]
I also could not recreate this issue. On both the nexus 9 and 10 tablets (which may or not be the problem) when I 
1. Create games in the game lobby.
2. Restart the app 
3. Login as a player already registered but not in a game yet
4. Go to the game screen, after 1 second the screen refreshes and the list of games loads, with no input from the user.

So, I don't know how that issue got created, because I have not been able to recreate on my emulators. Would it be an apk issue somehow?
