### ISSUE TITLE
Clicking draw dest card multiple times allows multiple draws

### ISSUE THREAD

**Issue by wunter8** [cs340tabyu/cs340Fall2017#292]

**Comment by dylanmrowe** [comment]
This happens if you click ANYTHING really fast (routes, dest cards, train cards). You can get past the turn restrictions. This is due to the way we're recording turn info - we only record a successful turn once the command is returned from the server. So if you click it twice before the command is retrieved, you get to do extra things.

**Comment by dylanmrowe** [comment]
I'll plan on fixing this.

**Comment by dylanmrowe** [comment]
Fixed.
